//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DOTNProjekt
{
    using System;
    using System.Collections.Generic;
    
    public partial class macke
    {
        public int id { get; set; }
        public string ime { get; set; }
        public double cijena { get; set; }
        public Nullable<int> drzava_id { get; set; }
    
        public virtual drzave drzave { get; set; }
    }
}
